---
title: "Biowulf_usage"
author: "Vishal Koparde, PhD [CCBR]"
date: "March 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE)
```

```{r echo=FALSE}
rm(list=ls())
#setwd("~/Desktop/Temp/biowulf_usage/")
library("ggplot2")
library("tidyverse")
library("reshape2")
library("plotly")
library("RColorBrewer")
n <- 201
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))

read_file<-function(filename){
  d=read.csv(file=filename,header=FALSE,sep="\t")
  sn=gsub(pattern = ".txt", replacement = "",x=filename)
  colnames(d)=c("username",paste0("T",sn))
  y=c("others",sum(d[21:nrow(d),2]))
  d=rbind(d[1:20,],y)
  return(d)
}

fj <- function(x,y) full_join(x,y,by="username")

hour_conversion<-function(hour){
  hour=as.integer(hour)
  ampm="am"
  if (hour>12){
    hour=hour-12
    ampm="pm"
  }
  newhour=paste(hour,ampm)
  return(newhour)
}
reformatdate<-function(x){
  m=list()
  m[["01"]]="Jan"
  m[["02"]]="Feb"
  m[["03"]]="Mar"
  m[["04"]]="Apr"
  m[["05"]]="May"
  m[["06"]]="Jun"
  m[["07"]]="Jul"
  m[["08"]]="Aug"
  m[["09"]]="Sep"
  m[["10"]]="Oct"
  m[["11"]]="Nov"
  m[["12"]]="Dec"
  
  month=substr(x,2,3)
  day=substr(x,4,5)
  hour=substr(x,8,9)
  newdate=paste(m[[month]],day,hour_conversion(hour))
  return(newdate)
}

files=list.files(path = ".",pattern = ".txt")
files=sort(files)
# filename=files[1]

usage=list()
for (i in 1:length(files)){
  usage[[i]]=read_file(files[i])
}
purrr::reduce(usage,fj) -> usagematrix
usagematrix %>% replace(is.na(.),0) %>% column_to_rownames(var="username")-> usagematrix
for (i in 1:ncol(usagematrix)){usagematrix[,i]=as.numeric(usagematrix[,i])}
usagematrix = as.data.frame(as.matrix(usagematrix))
usagematrix = usagematrix[order(rowSums(usagematrix),decreasing = TRUE),]
colnames(usagematrix) = unlist(lapply(colnames(usagematrix), reformatdate))
usagematrix %>% rownames_to_column(var="username") -> usagematrix
usagematrix$username <- reorder(usagematrix$username, rowSums(usagematrix[-1]))
usagematrix.melt = melt(usagematrix,id="username")
colnames(usagematrix.melt)=c("username","timestamp","ncpus_in_use")
dates=unique(substr(usagematrix.melt$timestamp,1,6))
users=as.vector(unique(usagematrix.melt$username))
daily_usage=matrix(ncol = 3, nrow = 0)
for (j in 1:length(dates)){
  days_usage=matrix(ncol = 3, nrow = 0)
  for (i in 1:length(users)){
    user=users[[i]]
    date=dates[[j]]
    mean_ncpus_used=mean(usagematrix.melt[grepl(date,usagematrix.melt$timestamp) & usagematrix.melt$username==user,]$ncpus_in_use)
    days_usage=rbind(days_usage,c(user,date,mean_ncpus_used))
  }
  days_usage=as.data.frame(days_usage)
  colnames(days_usage)=c("user","date","mean_ncpus_used")
  days_usage=days_usage[order(days_usage$mean_ncpus_used,decreasing = TRUE),]
  daily_usage=rbind(daily_usage,days_usage)
}
daily_usage=as.data.frame(daily_usage)
colnames(daily_usage)=c("user","date","mean_ncpus_used")
x=dcast(data=daily_usage,formula = user~date,value.var = "mean_ncpus_used")
x$rs=rowSums(x[-1])
x=x[order(x$rs,decreasing = TRUE),]
x$rs=NULL
x.melt=melt(x,id="user")
daily_usage=x.melt
colnames(daily_usage)=c("user","date","mean_ncpus_used")
daily_usage$mean_ncpus_used=as.numeric(daily_usage$mean_ncpus_used)
```
##Hourly
```{r pressure, echo=FALSE,fig.width=15,fig.height=9,fig.align='center'}
everyother_xlabels=levels(usagematrix.melt$timestamp)
everyother_xlabels[seq(2,length(everyother_xlabels),2)]=""
ggplotly(ggplot(usagematrix.melt,aes(x=timestamp,y=ncpus_in_use,fill=username))+
           geom_bar(stat = "identity", col="white")+
           scale_fill_manual(values=sample(col_vector,200,replace=TRUE))+theme_classic()+
           theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
           scale_x_discrete(labels = everyother_xlabels)
           )
```
##Daily
```{r test}
everyother_xlabels=levels(as.factor(daily_usage$date))
everyother_xlabels[seq(2,length(everyother_xlabels),2)]=""
ggplotly(ggplot(daily_usage,aes(x=date,y=mean_ncpus_used,fill=user))+
           geom_bar(stat = "identity", col="white")+
           scale_fill_manual(values=sample(col_vector,200,replace=TRUE))+theme_classic()+
           theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
           scale_x_discrete(labels = everyother_xlabels)
           )
```
