# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # pull_request:
    # branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: nciccbr/ccbr_baser:latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: My first action
        run: ls -alrth
      - name: run the docker
        run: |
          tar xzvf data.tar.gz
          Rscript -e "rmarkdown::render(input='biowulf_usage.Rmd')"
          cp biowulf_usage.html docs/index.html
      - name: ls again
        run: ls -alrth
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: docs/index.html
          commit-msg: Update resources
          github-token: ${{ secrets.GITHUB_TOKEN }}
